/**
 * Pure, lightweight trigger matcher for 03-work.
 * Has ZERO external imports to ensure near-zero cold startup overhead.
 */
export function isExplicit03WorkTrigger(prompt: string): boolean {
	if (!prompt) return false;
	const trimmed = prompt.trim();
	const lower = trimmed.toLowerCase();

	// 1. Direct skill invocation or slash command
	if (
		lower.startsWith("/skill:03-work") ||
		lower === "/skill:03"
	) {
		return true;
	}

	// 2. Strict keywords and natural language commands to start/resume 03 work
	const strictPatterns = [
		/^开始(03|干活|编码|实现|写代码)/,
		/^执行(03|03-work|干活)/,
		/^自主(干活|工作|编码)/,
		/^(继续|恢复)(干活|03|工作|work)/i,
		/^resume\s+(03|work)/i,
	];

	if (strictPatterns.some((p) => p.test(trimmed))) {
		return true;
	}

	// 3. Autonomous continuation follow-up prompt generated by the driver itself
	if (trimmed.startsWith("【03-work 自主循环驱动引擎")) {
		return true;
	}

	return false;
}
